There is a TODO application: two independent services talking over HTTP (REST): `todo-app` and `todo-ui`

== Context

The `todo` is a simple TODO application built in a old-school way: EJB components with servlets and JSF sitting on a single application server (wildfly).

However, as the business evolves - the UI is planned to be replaced by a modern, JavaScript based frontend application. As a part of refactoring initiative a new front-end has be designed and implemented: `todo-ui`, which is a Single Page Application, with an idea to communicate with the old application thrugh a set of REST-like HTTP calls.

== Task #{counter:task-front-end}

Based on the defined interfaces, extend the existing application and provide a set of required API.

What additional changes needs to be done to allow application to application communication, when deployed separately? How can the application still be developed separately but deployed as a monolith?

== How to run

The Pact is prepared by the JavaScript application. It states the expectation; what resources are expected from the provider.

It's expressed as a Pact contract created in the test phase. The pact is than passed over to provider.

The pact file is located in `todo-app/src/test/resources`. An Arquillian test is built to validate the contract (`TodoResourceProviderIT`)

The test is run as a part of Intergration Testing phase which can be triggered with Maven's `mvn clean verify`. It spins wildfly instance on pre-integration phase and stops it during post-integration phase.

Implement the missing methods in the `TodoResource` class for the test to successfully pass. 

////

== Task #{counter:task-front-end}

A new service has been added to the pool: a todo can hold additional link or image. The functionality is provided by a `todo-links` service, which is a full stack microservice. It provides both HTTP apis to store and retrieve links based on todo identifier, but can also provide ready made HTML snippets to be included on the page.

Provide integration with the new links service in a naive way (front-end is calling new service directly on different port)

== Task #{counter:task-front-end}

// https://en.wikipedia.org/wiki/Edge_Side_Includes

While the previous implementation is easy and robust, on a larger scale it can bring many problems (with configuration and operational management - to say the least). Other approaches include API Gateway pattern and UI Composition patterns.

The first one is fairly easy, where UI is using the gateway as a base API. On the downside, the UI and API tend to be monolithic (encapsulating the ecosystem underneath). The latter approach (UI Composition) unfortunately seem easier than it is.

Integrate the new links service through UI Composition.

////
